sonar.projectKey=vanshagarwal20_ResumeAI
sonar.organization=vanshagarwal20
sonar.host.url=https://sonarcloud.io

sonar.projectName=ResumeAI
sonar.sourceEncoding=UTF-8

sonar.sources=ai-service/src/main/java,api-gateway/src/main/java,auth-service/src/main/java,eureka-server/src/main/java,export-service/src/main/java,jobmatch-service/src/main/java,notification-service/src/main/java,resume-service/src/main/java,section-service/src/main/java,template-service/src/main/java
sonar.tests=ai-service/src/test/java,api-gateway/src/test/java,auth-service/src/test/java,eureka-server/src/test/java,export-service/src/test/java,jobmatch-service/src/test/java,notification-service/src/test/java,resume-service/src/test/java,section-service/src/test/java,template-service/src/test/java

sonar.java.binaries=ai-service/target/classes,api-gateway/target/classes,auth-service/target/classes,eureka-server/target/classes,export-service/target/classes,jobmatch-service/target/classes,notification-service/target/classes,resume-service/target/classes,section-service/target/classes,template-service/target/classes
sonar.coverage.jacoco.xmlReportPaths=ai-service/target/site/jacoco/jacoco.xml,api-gateway/target/site/jacoco/jacoco.xml,auth-service/target/site/jacoco/jacoco.xml,eureka-server/target/site/jacoco/jacoco.xml,export-service/target/site/jacoco/jacoco.xml,jobmatch-service/target/site/jacoco/jacoco.xml,notification-service/target/site/jacoco/jacoco.xml,resume-service/target/site/jacoco/jacoco.xml,section-service/target/site/jacoco/jacoco.xml,template-service/target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**,**/.mvn/**,**/mvnw,**/mvnw.cmd
